semilla_primigenia: 500009.0
experimento: 9102.0
dataset: analistajr_competencia_2025.csv.gz
CA:
  metodo: MachineLearning
DR:
  metodo: deflacion
FE_rf:
  arbolitos: 20.0
  hojas_por_arbol: 16.0
  datos_por_hoja: 100.0
  mtry_ratio: 0.2
  train:
    clase01_valor1:
    - BAJA+2
    - BAJA+1
    training:
    - 202101.0
    - 202102.0
    - 202103.0
  lgb_param:
    num_iterations: 20.0
    num_leaves: 16.0
    min_data_in_leaf: 100.0
    feature_fraction_bynode: 0.2
    boosting: rf
    bagging_fraction: 0.6321206
    bagging_freq: 1.0
    feature_fraction: 1.0
    max_bin: 31
    objective: binary
    first_metric_only: yes
    boost_from_average: yes
    feature_pre_filter: no
    force_row_wise: yes
    verbosity: -100.0
    max_depth: -1
    min_gain_to_split: 0.0
    min_sum_hessian_in_leaf: 0.001
    lambda_l1: 0.0
    lambda_l2: 0.0
    pos_bagging_fraction: 1.0
    neg_bagging_fraction: 1.0
    is_unbalance: no
    scale_pos_weight: 1.0
    drop_rate: 0.1
    max_drop: 50.0
    skip_drop: 0.5
    extra_trees: no
trainingstrategy:
  validate: 202107.0
  training:
  - 201901.0
  - 201902.0
  - 201903.0
  - 201904.0
  - 201905.0
  - 201906.0
  - 201907.0
  - 201908.0
  - 201909.0
  - 201910.0
  - 201911.0
  - 201912.0
  - 202001.0
  - 202002.0
  - 202003.0
  - 202004.0
  - 202005.0
  - 202006.0
  - 202007.0
  - 202008.0
  - 202009.0
  - 202010.0
  - 202011.0
  - 202012.0
  - 202101.0
  - 202102.0
  - 202103.0
  - 202104.0
  - 202105.0
  training_pct: 1.0
  positivos:
  - BAJA+1
  - BAJA+2
  final_train:
  - 201901.0
  - 201902.0
  - 201903.0
  - 201904.0
  - 201905.0
  - 201906.0
  - 201907.0
  - 201908.0
  - 201909.0
  - 201910.0
  - 201911.0
  - 201912.0
  - 202001.0
  - 202002.0
  - 202003.0
  - 202004.0
  - 202005.0
  - 202006.0
  - 202007.0
  - 202008.0
  - 202009.0
  - 202010.0
  - 202011.0
  - 202012.0
  - 202101.0
  - 202102.0
  - 202103.0
  - 202104.0
  - 202105.0
  - 202106.0
  - 202107.0
  future: 202109.0
hipeparametertuning:
  num_interations: 20.0
  hs:
    pars:
      num_leaves:
        id: num_leaves
        type: integer
        len: 1
        lower: 8
        upper: 512
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      min_data_in_leaf:
        id: min_data_in_leaf
        type: integer
        len: 1
        lower: 10
        upper: 4096
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      feature_fraction:
        id: feature_fraction
        type: numeric
        len: 1
        lower: 0.2
        upper: 1.0
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      learning_rate:
        id: learning_rate
        type: numeric
        len: 1
        lower: 0.005
        upper: 0.3
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
    forbidden: ~
lgbm:
  param_fijos:
    objective: binary
    metric: auc
    first_metric_only: yes
    boost_from_average: yes
    feature_pre_filter: no
    verbosity: -100.0
    force_row_wise: yes
    seed: 500009.0
    max_bin: 31.0
    learning_rate: 0.005
    num_iterations: 9999.0
    early_stopping_rounds: 1000.0
out:
  lgbm:
    mejores_hiperparametros:
      num_leaves: 122
      min_data_in_leaf: 2068
      feature_fraction: 0.2221825
      learning_rate: 0.0050685
      num_iterations: 1579
kaggle:
  competencia: labol-2025-virtual-analista-jr
  cortes:
  - 1800.0
  - 1900.0
  - 2000.0
  - 2100.0
  - 2200.0
  - 2300.0
  - 2400.0
